Support multiple tokens
jswetzen/docker-entrydns pull request #1
Opened 2017-08-11 14:41 UTC by mach-kernel

Hey there,

I don't know if this is a very common use case but this is pretty useful to me and doesn't really break anything that is already there. 

Thanks!

2017-08-12 05:49 UTC, jswetzen commented
Hey, thanks for contributing! I don't have any use for it personally, supporting multiple tokens is a good addition. Your "oops" commit seems to be added to the wrong branch though, so it doesn't show up. I'll make a review with some comments too.

2017-08-12 06:01 UTC, jswetzen requested changes

2017-08-12 06:01 UTC, jswetzen commented on update_entrydns.sh
> +        while read -d "," part; do
Wouldn't this work on a single token too (no commas)? Then you don't have to treat them as different cases. Does the while loop work without bash?

2017-08-12 06:01 UTC, jswetzen commented on Dockerfile
> +RUN apk add --no-cache curl bash
Is bash needed? (See further comments)

2017-08-12 06:01 UTC, jswetzen commented on update_entrydns.sh
> +([ -z "${AUTH_TOKEN}" ] && [ -z "${AUTH_TOKENS}" ]) && { echo "=> AUTH_TOKEN(S) cannot be empty" && exit 1; }
Is this the part that needs bash? Use only "AUTH_TOKEN" and it's not needed any more.

2017-08-13 21:55 UTC, mach-kernel commented
@jswetzen I tried with `sh` on OS X and was successful in getting the script to run, but not from the Alpine image. I saw your change requests and clean this up -- I should have done so before opening the PR since my solution was very "quick rig up" to replace an internal script we had. 

Thanks! I'll get to it 🚀

2017-08-14 06:24 UTC, jswetzen commented
@mach-kernel Ah yes, different `sh` behaviour makes development difficult. I became a bit obsessed with minimal dependencies when I found Alphine, but `bash` is absolutely fine. 👌
If you can handle the list and single token as the same variable I'll merge it right away!

2017-08-24 19:29 UTC, jswetzen commented
Have you made any progress on this?

2017-08-25 14:29 UTC, mach-kernel commented
@jswetzen it's been a busy few weeks, I'll knock this out today!

2017-08-29 17:25 UTC, mach-kernel commented
@jswetzen Today actually meant in 4 days, but there it is 😸 . We do however need `bash` for consistent tokenization support. I'm with it only on reason of opting out from a code golf adventure on finding the best way to do it with `sh` 😆

2017-09-08 17:20 UTC, mach-kernel commented
@jswetzen any time to look these over?

2017-09-10 21:35 UTC, jswetzen commented
I had a look, added ShellCheck linting and thought maybe it's just as easy to do it with a for loop. I couldn't find a way to update your pull request, but could you have a look at #3?

2017-09-12 18:44 UTC, jswetzen commented
Sorry for not accepting your solution @mach-kernel, but I added ShellCheck linting and saw that there were some problems with my original script. Then I found that a `for` loop would do the tokenization fine if the Internal Field Separator was changed, so it made for a simple `sh` solution. I'm thankful for your contribution and hope you will find that this image works well for your use case too now.

2017-09-12 18:44 UTC, closed without merging

2017-09-12 21:12 UTC, mach-kernel commented
That's awesome! No worries at all.